# Generated by Django 5.1 on 2024-08-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_type_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ItemType',
        ),
    ]
