# Generated by Django 5.1 on 2024-08-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
