# Generated by Django 5.1 on 2024-10-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_seller_alter_customer_email_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
